all:
	cd ./a7/ && $(MAKE) && cd ../a6/ && $(MAKE) && cd ../

clean:
	cd ./a7 && $(MAKE) clean && cd ../a6/ && $(MAKE) clean && cd ../

run-a7:
	cd ./a7 && $(MAKE) run && cd ../

run-a6:
	cd ./a6 && $(MAKE) run && cd ../

